Port to Python 3
zopefoundation/zope.app.pagetemplate pull request #1
Opened 2017-04-20 17:47 UTC by jamadden

2017-04-21 16:19 UTC, tseaver requested changes

2017-04-21 16:19 UTC, tseaver commented on setup.py
> +          'Programming Language :: Python:: 3.5',
Python 3.4 support, please.

2017-04-21 16:19 UTC, tseaver commented on src/zope/app/pagetemplate/interfaces.py
> +from __future__ import print_function, absolute_import, division
Not needed.

2017-04-21 16:19 UTC, tseaver commented on src/zope/app/pagetemplate/talesapi.py
> +from __future__ import print_function, absolute_import, division
Not needed.

2017-04-21 16:19 UTC, tseaver commented on src/zope/app/pagetemplate/tests/test_bwc.py
> +from __future__ import print_function, absolute_import, division
Not needed.

2017-04-21 16:19 UTC, tseaver commented on src/zope/app/pagetemplate/tests/test_talesapi.py
> +from __future__ import print_function, absolute_import, division
Not needed.

2017-04-21 16:19 UTC, tseaver commented on src/zope/app/pagetemplate/tests/test_talesapi.py
> -    """
Yay!

2017-04-21 16:19 UTC, tseaver commented on src/zope/app/pagetemplate/tests/test_urlquote.py
> +from __future__ import absolute_import, print_function, division
Not needed.

2017-04-21 16:19 UTC, tseaver commented on src/zope/app/pagetemplate/urlquote.py
> +from __future__ import print_function, absolute_import, division
Not needed.

2017-04-21 16:49 UTC, jamadden commented on src/zope/app/pagetemplate/tests/test_talesapi.py
> -    """
There were few enough doctests here that I was able to get away with not using a `RENormalizer` and just convert to unit tests 😄

2017-04-22 13:25 UTC, mgedmin approved these changes
lgtm

2017-04-22 13:25 UTC, mgedmin commented on .travis.yml
> +  - coverage run -m zope.testrunner --test-path=src  --auto-color --auto-progress
My inner pedant cannot not notice the indentation change here.

2017-04-22 13:31 UTC, jamadden commented on .travis.yml
> +  - coverage run -m zope.testrunner --test-path=src  --auto-color --auto-progress
My bad. Corrected.

2017-04-22 13:31 UTC, jamadden commented
Thanks! A PyPI release would be handy when convenient.

2017-04-22 13:32 UTC, merged

2017-04-22 13:53 UTC, mgedmin commented
@jamadden what's your PyPI username?

2017-04-22 13:55 UTC, jamadden commented
> what's your PyPI username?
@mgedmin It's... jamadden. I'm predictable. Mostly 😉

2017-04-22 13:57 UTC, mgedmin commented
You now have PyPI rights to zope.app.pagetemplate.  Congratulations!

2017-04-22 14:00 UTC, jamadden commented
Cool, thanks. If there are no objections, I'll go ahead and release this soon.